project:
  type: website
  resources:
    - CNAME

website:
  title: "Jae-Young Son"
  navbar:
    left:
      - about.qmd
      - text: CV
        href: cv.qmd
      - publications.qmd
      - tutorials.qmd
      - blog.qmd

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    css: styles.css

editor: visual
